name: Check Build Docs

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths: 
      - 'docs-src/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'docs-src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm i

    - run: npm run docs
    
    - name: Check for uncommited changes
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          echo ----------------------------------------
          echo git status
          echo ----------------------------------------
          git status
          echo ----------------------------------------
          echo git diff
          echo ----------------------------------------
          git diff
          echo ----------------------------------------
          echo Troubleshooting
          echo ----------------------------------------
          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && npm run build && npm run format && npm run docs"
          exit 1
        fi
