name: Check Build Docs

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'
      - '.vscode/**'
      - 'assets/**'
      - 'dev/**'
      - 'src/**'
  pull_request:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'
      - '.vscode/**'
      - 'assets/**'
      - 'dev/**'
      - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm i

    - run: npm run docs
    
    - name: Check for uncommited changes
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          echo ----------------------------------------
          echo git status
          echo ----------------------------------------
          git status
          echo ----------------------------------------
          echo git diff
          echo ----------------------------------------
          git diff
          echo ----------------------------------------
          echo Troubleshooting
          echo ----------------------------------------
          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && npm run build && npm run format && npm run docs"
          exit 1
        fi
