name: Publish Npm - Dev

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Init Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org/
        
    - run: npm i
    - run: npm run build:dist

    - run: npm version prerelease

    - run: npm publish --tag dev --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Git Push
      run: |
        git push origin
