name: Publish Npm - Dev

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        
    - run: npm i
    - run: npm run build:dist
    - run: npm publish --tag dev --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
