name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js v14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        
    - run: npm ci
    
    - run: npm run docs
        
    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-gen
