name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org/
        
    - run: npm i
    - run: npm run build:dist

    - name: Release - Create Draft for Release
      id: create_draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate version - Cut away the first letter (v)
      id: create_version
      run: |
        tag_name=${{ steps.create_draft.outputs.tag_name }}
        echo "::set-output name=version::$(echo ${tag_name:1})"

    - run: npm version ${{ steps.create_version.outputs.version }}

    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Git Push
      run: |
        git push origin

  after_release:
    runs-on: ubuntu-latest
    needs: [publish]

    steps:
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_branch: "develop"
        pr_title: "Sync back after release"
        pr_body: "An automated PR to sync changes back"
