name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '5 2 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_GH_TOKEN }}
